PREFIX uct: <https://example.org/uct#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?superclass
WHERE {
    uct:DepartmentOfKnowledgeAndInformationStewardship rdfs:subClassOf ?superclass .
}