PREFIX recipeim: <https://example.org/recipe/imperial#>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?multiplier ?offset
WHERE {
    recipeim:Fahrenheit qudt:conversionMultiplier ?multiplier ;
                        qudt:conversionOffset ?offset .
}